name: Export Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Export APK
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.4/Godot_v4.4-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.4/export_templates/Godot_v4.4-stable_export_templates.tpz

          relative_project_path: "project"
          export_debug: true
          presets_to_export: |
            Android
          relative_export_path: "build"
          cache: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/*.apk
