name: Export Android APK

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Export APK
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz

          relative_project_path: "project"
          export_debug: true
          presets_to_export: |
            Android
          relative_export_path: "project/build"
          cache: true

      - name: Read app version from Godot project
        run: |
          VER=$(awk '
            $0 ~ /^\[application\]/ {in_app=1; next}
            $0 ~ /^\[/ {in_app=0}
            in_app && $0 ~ /^config\/version=/ {
              gsub(/.*="/,""); gsub(/"$/,""); print; exit
            }' project/project.godot)
          [ -z "$VER" ] && VER="0.0.0"
          echo "APP_VERSION=$VER" >> "$GITHUB_ENV"

      - name: Rename APK with version
        run: |
          mv project/build/Android/evidence.apk \
            project/build/Android/evidence-v${{ env.APP_VERSION }}-build${{ github.run_number }}.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: project/build/**/*.apk
          retention-days: 7

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.APP_VERSION }} 
          commitish: ${{ github.sha }}
          release_name: "Android debug build #${{ github.run_number }}"
          draft: false
          prerelease: true

      - name: Upload APK to Release (raw .apk)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: project/build/Android/evidence.apk
          asset_name: evidence.apk
          asset_content_type: application/vnd.android.package-archive