name: Build Android (Godot 4)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  WORKING_DIRECTORY: project

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Export Android APK
        uses: dulvui/godot-android-export@v4.0.4
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          working-directory: ${{ env.WORKING_DIRECTORY }}
          preset: "Android"
          export-type: "release"   # release o debug

      - name: Subir artefacto APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ env.WORKING_DIRECTORY }}/*.apk
