name: Build Android (Godot 4)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.2.2
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true  # por si usas Git LFS para assets

      - name: Export APK (release)
        working-directory: project
        run: |
          mkdir -p build
          godot --headless --verbose \
            --path . \
            --export-release "Android" build/evidence.apk

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: evidence-apk
          path: project/build/evidence.apk
